version: '3'

services:
  mysql:
    container_name: java_ddd_template-database
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=lechuga
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS domain_events; CREATE DATABASE IF NOT EXISTS accounts;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  rabbitmq:
    container_name: java_ddd_template-rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=lechuga

  java:
    container_name: java_ddd_template-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8030:8080
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    tty: true
    depends_on:
      - mysql
